<?php

// scoper-autoload.php @generated by PhpScoper

$loader = (static function () {
    // Backup the autoloaded Composer files
    $existingComposerAutoloadFiles = isset($GLOBALS['__composer_autoload_files']) ? $GLOBALS['__composer_autoload_files'] : [];

    $loader = require_once __DIR__.'/autoload.php';
    // Ensure InstalledVersions is available
    $installedVersionsPath = __DIR__.'/composer/InstalledVersions.php';
    if (file_exists($installedVersionsPath)) require_once $installedVersionsPath;

    // Restore the backup and ensure the excluded files are properly marked as loaded
    $GLOBALS['__composer_autoload_files'] = \array_merge(
        $existingComposerAutoloadFiles,
        \array_fill_keys([], true)
    );

    return $loader;
})();

// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
if (!function_exists('humbug_phpscoper_expose_class')) {
    function humbug_phpscoper_expose_class($exposed, $prefixed) {
        if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
            spl_autoload_call($prefixed);
        }
    }
}
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Default_Registry', 'WP_Typography\Vendor\PHP_Typography\Fixes\Default_Registry');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Hyphenate_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Compounds_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Hyphenate_Compounds_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Smart_Dashes_Hyphen_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Smart_Dashes_Hyphen_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Abstract_Token_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Abstract_Token_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Wrap_URLs_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Wrap_URLs_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Wrap_Emails_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Wrap_Emails_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Token_Fixes\Wrap_Hard_Hyphens_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Wrap_Hard_Hyphens_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Registry', 'WP_Typography\Vendor\PHP_Typography\Fixes\Registry');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Space_Collapse_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Space_Collapse_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Fractions_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Fractions_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Dash_Spacing_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Dash_Spacing_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Dewidow_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Dewidow_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Style_Numbers_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Numbers_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Maths_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Maths_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Diacritics_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Diacritics_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Ordinal_Suffix_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Ordinal_Suffix_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Process_Words_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Process_Words_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Area_Units_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Area_Units_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Style_Hanging_Punctuation_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Hanging_Punctuation_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Simple_Style_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Simple_Style_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Quotes_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Quotes_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Exponents_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Exponents_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Style_Caps_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Caps_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Single_Character_Word_Spacing_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Single_Character_Word_Spacing_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Numbered_Abbreviation_Spacing_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Numbered_Abbreviation_Spacing_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Abstract_Node_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Abstract_Node_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Unit_Spacing_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Unit_Spacing_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Dashes_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Dashes_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Style_Initial_Quotes_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Initial_Quotes_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\French_Punctuation_Spacing_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\French_Punctuation_Spacing_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Marks_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Marks_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Style_Ampersands_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Ampersands_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Simple_Regex_Replacement_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Simple_Regex_Replacement_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Classes_Dependent_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Classes_Dependent_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fixes\Smart_Ellipses_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Ellipses_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Fixes\Node_Fix', 'WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fix');
humbug_phpscoper_expose_class('PHP_Typography\Settings\Simple_Quotes', 'WP_Typography\Vendor\PHP_Typography\Settings\Simple_Quotes');
humbug_phpscoper_expose_class('PHP_Typography\Settings\Simple_Dashes', 'WP_Typography\Vendor\PHP_Typography\Settings\Simple_Dashes');
humbug_phpscoper_expose_class('PHP_Typography\Settings\Quote_Style', 'WP_Typography\Vendor\PHP_Typography\Settings\Quote_Style');
humbug_phpscoper_expose_class('PHP_Typography\Settings\Quotes', 'WP_Typography\Vendor\PHP_Typography\Settings\Quotes');
humbug_phpscoper_expose_class('PHP_Typography\Settings\Dashes', 'WP_Typography\Vendor\PHP_Typography\Settings\Dashes');
humbug_phpscoper_expose_class('PHP_Typography\Settings\Dash_Style', 'WP_Typography\Vendor\PHP_Typography\Settings\Dash_Style');
humbug_phpscoper_expose_class('PHP_Typography\U', 'WP_Typography\Vendor\PHP_Typography\U');
humbug_phpscoper_expose_class('PHP_Typography\RE', 'WP_Typography\Vendor\PHP_Typography\RE');
humbug_phpscoper_expose_class('PHP_Typography\PHP_Typography', 'WP_Typography\Vendor\PHP_Typography\PHP_Typography');
humbug_phpscoper_expose_class('PHP_Typography\Text_Parser', 'WP_Typography\Vendor\PHP_Typography\Text_Parser');
humbug_phpscoper_expose_class('PHP_Typography\Strings', 'WP_Typography\Vendor\PHP_Typography\Strings');
humbug_phpscoper_expose_class('PHP_Typography\Hyphenator\Trie_Node', 'WP_Typography\Vendor\PHP_Typography\Hyphenator\Trie_Node');
humbug_phpscoper_expose_class('PHP_Typography\Hyphenator\Cache', 'WP_Typography\Vendor\PHP_Typography\Hyphenator\Cache');
humbug_phpscoper_expose_class('PHP_Typography\Settings', 'WP_Typography\Vendor\PHP_Typography\Settings');
humbug_phpscoper_expose_class('PHP_Typography\DOM', 'WP_Typography\Vendor\PHP_Typography\DOM');
humbug_phpscoper_expose_class('PHP_Typography\Hyphenator', 'WP_Typography\Vendor\PHP_Typography\Hyphenator');
humbug_phpscoper_expose_class('PHP_Typography\Text_Parser\Token', 'WP_Typography\Vendor\PHP_Typography\Text_Parser\Token');

return $loader;
